services:
  phpfpm:
    image: php:8.3-fpm
    container_name: phpfpm
    build: docker/php
    working_dir: /var/www/html
    volumes:
      - ./back:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./back/public:/var/www/html:ro,cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - phpfpm
    networks:
      - app-network

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffreo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nextjs:
    container_name: nextjs
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

  mercure:
    image: dunglas/mercure
    container_name: mercure
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      MERCURE_JWT_SECRET: '7a427bbd14e9f80bbfc16c08ddd50267975a15ba326d9f98262724d3e7e26317'
      MERCURE_PUBLISHER_JWT_KEY: '28deae2d14d7af172dafa6bc8fe01f95284ad23264b83a16383dd32dcb6869dd'
      MERCURE_SUBSCRIBER_JWT_KEY: '28deae2d14d7af172dafa6bc8fe01f95284ad23264b83a16383dd32dcb6869dd'

      MERCURE_ALLOW_ANONYMOUS: "1"
      MERCURE_CORS_ALLOWED_ORIGINS: '*'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
