services:
  phpfpm:
    image: php:8.3-fpm
    container_name: phpfpm
    build: docker/php
    working_dir: /var/www/html
    volumes:
      - ./back:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./back/public:/var/www/html:ro,cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - phpfpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
